"""Regenerate ThemePalettes.kt from the web frontend's Tailwind palette.

Kotlin twin of ios/scripts/gen_palettes.py — same source file, same oklch → sRGB
conversion, so the three clients paint identical brand colours. Run it whenever the
web's THEME_PALETTES choices change:

    python3 android/scripts/gen_palettes.py
"""

import math
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSS = os.path.join(ROOT, "frontend", "node_modules", "tailwindcss", "theme.css")
OUT = os.path.join(
    ROOT, "android", "app", "src", "main", "java", "com", "ivanlee",
    "financetracker", "ui", "theme", "ThemePalettes.kt",
)

NAMES = ["sky", "indigo", "rose", "emerald", "blue", "fuchsia", "orange", "yellow", "mauve", "slate"]
SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]


def oklch_to_srgb(L, C, H):
    h = math.radians(H)
    a, b = C * math.cos(h), C * math.sin(h)
    # oklab -> lms
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    # lms -> linear srgb
    r = +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    bb = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s

    def gamma(x):
        x = max(0.0, min(1.0, x))
        return 12.92 * x if x <= 0.0031308 else 1.055 * (x ** (1 / 2.4)) - 0.055

    return tuple(gamma(v) for v in (r, g, bb))


def hex_argb(rgb):
    r, g, b = (int(round(v * 255)) for v in rgb)
    return f"0xFF{r:02X}{g:02X}{b:02X}"


text = open(CSS).read()
pattern = re.compile(r"--color-(\w+)-(\d+):\s*oklch\(([\d.]+)%\s+([\d.]+)\s+([\d.]+)\)")
colors = {}
for name, shade, L, C, H in pattern.findall(text):
    if name in NAMES:
        colors[(name, int(shade))] = oklch_to_srgb(float(L) / 100, float(C), float(H))

missing = [(n, s) for n in NAMES for s in SHADES if (n, s) not in colors]
assert not missing, f"missing: {missing}"

out = [
    "package com.ivanlee.financetracker.ui.theme",
    "",
    "import androidx.compose.ui.graphics.Color",
    "",
    "// Generated by android/scripts/gen_palettes.py from the web frontend's Tailwind palette",
    "// (frontend/node_modules/tailwindcss/theme.css, oklch converted to sRGB). Same scales the",
    "// web dashboard's ThemeContext and the iOS ThemePalettes.swift use. Do not edit by hand.",
    "",
    "object ThemePalettes {",
    "    val all: Map<String, Palette> = mapOf(",
]
for name in NAMES:
    entries = ", ".join(
        f"{s} to Color({hex_argb(colors[(name, s)])})" for s in SHADES
    )
    out.append(f'        "{name}" to Palette(mapOf({entries})),')
out += ["    )", "}", ""]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(out))
print(f"wrote {OUT} with {len(colors)} colors")
