"""add_target_amount_to_subportfolio

Revision ID: 0b51bc0dd274
Revises: 9d0dae805819
Create Date: 2026-05-09 17:04:19.837025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b51bc0dd274'
down_revision: Union[str, Sequence[str], None] = '9d0dae805819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_portfolios', sa.Column('target_amount', sa.Numeric(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_portfolios', 'target_amount', schema='finance_tracker')
    # ### end Alembic commands ###
