"""budgets support multiple categories

Revision ID: 1754a7384d79
Revises: 956575644b4d
Create Date: 2026-07-28 20:34:56.921561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1754a7384d79'
down_revision: Union[str, Sequence[str], None] = '956575644b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_tracker.budgets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_tracker.categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['finance_tracker.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category_id', 'owner_user_id', name='uq_budget_category_household_category_owner'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_budget_categories_budget_id'), 'budget_categories', ['budget_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_budget_categories_category_id'), 'budget_categories', ['category_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_budget_categories_household_id'), 'budget_categories', ['household_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_budget_categories_id'), 'budget_categories', ['id'], unique=False, schema='finance_tracker')

    # Backfill: every existing budget's single category becomes its first (and
    # only) row in the new join table before the old column is dropped.
    op.execute(
        """
        INSERT INTO finance_tracker.budget_categories
            (id, budget_id, category_id, household_id, owner_user_id)
        SELECT gen_random_uuid(), id, category_id, household_id, owner_user_id
        FROM finance_tracker.budgets
        """
    )

    op.drop_index(op.f('ix_finance_tracker_budgets_category_id'), table_name='budgets', schema='finance_tracker')
    op.drop_constraint(op.f('uq_budget_household_category_owner'), 'budgets', schema='finance_tracker', type_='unique')
    op.drop_constraint(op.f('budgets_category_id_fkey'), 'budgets', schema='finance_tracker', type_='foreignkey')
    op.drop_column('budgets', 'category_id', schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True), schema='finance_tracker')
    op.create_foreign_key(op.f('budgets_category_id_fkey'), 'budgets', 'categories', ['category_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker')

    # Backfill: a budget with several categories can only carry one on the way
    # back down, so keep the earliest-added one (arbitrary but deterministic).
    op.execute(
        """
        UPDATE finance_tracker.budgets AS b
        SET category_id = bc.category_id
        FROM (
            SELECT DISTINCT ON (budget_id) budget_id, category_id
            FROM finance_tracker.budget_categories
            ORDER BY budget_id, id
        ) AS bc
        WHERE bc.budget_id = b.id
        """
    )
    op.create_unique_constraint(op.f('uq_budget_household_category_owner'), 'budgets', ['household_id', 'category_id', 'owner_user_id'], schema='finance_tracker', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_finance_tracker_budgets_category_id'), 'budgets', ['category_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_budget_categories_id'), table_name='budget_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_budget_categories_household_id'), table_name='budget_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_budget_categories_category_id'), table_name='budget_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_budget_categories_budget_id'), table_name='budget_categories', schema='finance_tracker')
    op.drop_table('budget_categories', schema='finance_tracker')
    # ### end Alembic commands ###
