"""Baseline schema

Revision ID: 1977fc11e92d
Revises: 
Create Date: 2026-05-01 15:09:44.849736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1977fc11e92d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_access', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'OWNER', 'VIEWER'",
               existing_nullable=True)
    op.create_index(op.f('ix_account_access_id'), 'account_access', ['id'], unique=False)
    op.drop_constraint(op.f('account_access_user_id_fkey'), 'account_access', type_='foreignkey')
    op.drop_constraint(op.f('account_access_account_id_fkey'), 'account_access', type_='foreignkey')
    op.create_foreign_key(None, 'account_access', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'account_access', 'financial_accounts', ['account_id'], ['id'])
    op.alter_column('account_balances', 'balance',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_account_balances_id'), 'account_balances', ['id'], unique=False)
    op.drop_constraint(op.f('account_balances_account_id_fkey'), 'account_balances', type_='foreignkey')
    op.create_foreign_key(None, 'account_balances', 'financial_accounts', ['account_id'], ['id'])
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'Transport', 'Salary', 'Dividends'",
               existing_nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="'INCOME' or 'EXPENSE'",
               existing_nullable=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_constraint(op.f('categories_household_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'households', ['household_id'], ['id'])
    op.alter_column('dividends', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Assigns cash yield to the specific portfolio',
               existing_nullable=True)
    op.alter_column('dividends', 'amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.drop_constraint(op.f('dividends_account_id_fkey'), 'dividends', type_='foreignkey')
    op.drop_constraint(op.f('dividends_asset_id_fkey'), 'dividends', type_='foreignkey')
    op.drop_constraint(op.f('dividends_household_id_fkey'), 'dividends', type_='foreignkey')
    op.drop_constraint(op.f('dividends_sub_portfolio_id_fkey'), 'dividends', type_='foreignkey')
    op.create_foreign_key(None, 'dividends', 'financial_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'dividends', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'dividends', 'households', ['household_id'], ['id'])
    op.create_foreign_key(None, 'dividends', 'sub_portfolios', ['sub_portfolio_id'], ['id'])
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.alter_column('financial_accounts', 'liquidity',
               existing_type=postgresql.ENUM('liquid', 'market_liquid', 'time_locked', 'retirement', name='liquidity_status'),
               type_=sa.Enum('liquid', 'market_liquid', 'time_locked', 'retirement', name='liquiditystatus'),
               existing_nullable=True)
    op.alter_column('financial_accounts', 'tax_status',
               existing_type=postgresql.ENUM('taxable', 'tax_deferred', 'tax_free', name='tax_treatment'),
               type_=sa.Enum('taxable', 'tax_deferred', 'tax_free', name='taxtreatment'),
               existing_nullable=True)
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.drop_constraint(op.f('financial_accounts_household_id_fkey'), 'financial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'financial_accounts', 'households', ['household_id'], ['id'])
    op.alter_column('household_members', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'ADMIN', 'EDITOR', 'VIEWER'",
               existing_nullable=True)
    op.create_index(op.f('ix_household_members_id'), 'household_members', ['id'], unique=False)
    op.drop_constraint(op.f('household_members_user_id_fkey'), 'household_members', type_='foreignkey')
    op.drop_constraint(op.f('household_members_household_id_fkey'), 'household_members', type_='foreignkey')
    op.create_foreign_key(None, 'household_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'household_members', 'households', ['household_id'], ['id'])
    op.alter_column('households', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'The Smith Family' or 'Ivan Personal'",
               existing_nullable=True)
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.alter_column('portfolio_access', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'OWNER', 'VIEWER'",
               existing_nullable=True)
    op.create_index(op.f('ix_portfolio_access_id'), 'portfolio_access', ['id'], unique=False)
    op.drop_constraint(op.f('portfolio_access_user_id_fkey'), 'portfolio_access', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_access_sub_portfolio_id_fkey'), 'portfolio_access', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_access', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'portfolio_access', 'sub_portfolios', ['sub_portfolio_id'], ['id'])
    op.alter_column('portfolio_snapshots', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Separates AAPL in your Risky vs Core bags',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'current_price',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'current_value_home_currency',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'average_cost_basis',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.drop_constraint(op.f('portfolio_snapshots_sub_portfolio_id_fkey'), 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_snapshots_asset_id_fkey'), 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_snapshots_household_id_fkey'), 'portfolio_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_snapshots', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'portfolio_snapshots', 'households', ['household_id'], ['id'])
    op.create_foreign_key(None, 'portfolio_snapshots', 'sub_portfolios', ['sub_portfolio_id'], ['id'])
    op.alter_column('sub_portfolios', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'Core Retirement', 'House Downpayment', 'YOLO Crypto'",
               existing_nullable=True)
    op.alter_column('sub_portfolios', 'risk_profile',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="e.g., 'High', 'Medium', 'Low'",
               existing_nullable=True)
    op.alter_column('sub_portfolios', 'target_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Optional: e.g., 2028-06-01 for the downpayment',
               existing_nullable=True)
    op.create_index(op.f('ix_sub_portfolios_id'), 'sub_portfolios', ['id'], unique=False)
    op.drop_constraint(op.f('sub_portfolios_household_id_fkey'), 'sub_portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'sub_portfolios', 'households', ['household_id'], ['id'])
    op.alter_column('trades', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Which bucket does this trade belong to?',
               existing_nullable=True)
    op.alter_column('trades', 'price',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.drop_constraint(op.f('trades_sub_portfolio_id_fkey'), 'trades', type_='foreignkey')
    op.drop_constraint(op.f('trades_household_id_fkey'), 'trades', type_='foreignkey')
    op.drop_constraint(op.f('trades_account_id_fkey'), 'trades', type_='foreignkey')
    op.drop_constraint(op.f('trades_asset_id_fkey'), 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'sub_portfolios', ['sub_portfolio_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'financial_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'households', ['household_id'], ['id'])
    op.alter_column('transactions', 'amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_constraint(op.f('transactions_account_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'financial_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('transactions_account_id_fkey'), 'transactions', 'financial_accounts', ['account_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(op.f('trades_asset_id_fkey'), 'trades', 'assets', ['asset_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('trades_account_id_fkey'), 'trades', 'financial_accounts', ['account_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('trades_household_id_fkey'), 'trades', 'households', ['household_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('trades_sub_portfolio_id_fkey'), 'trades', 'sub_portfolios', ['sub_portfolio_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.alter_column('trades', 'price',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.alter_column('trades', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment='Which bucket does this trade belong to?',
               existing_nullable=True)
    op.drop_constraint(None, 'sub_portfolios', type_='foreignkey')
    op.create_foreign_key(op.f('sub_portfolios_household_id_fkey'), 'sub_portfolios', 'households', ['household_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_sub_portfolios_id'), table_name='sub_portfolios')
    op.alter_column('sub_portfolios', 'target_date',
               existing_type=sa.DATE(),
               comment='Optional: e.g., 2028-06-01 for the downpayment',
               existing_nullable=True)
    op.alter_column('sub_portfolios', 'risk_profile',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'High', 'Medium', 'Low'",
               existing_nullable=True)
    op.alter_column('sub_portfolios', 'name',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'Core Retirement', 'House Downpayment', 'YOLO Crypto'",
               existing_nullable=True)
    op.drop_constraint(None, 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_snapshots_household_id_fkey'), 'portfolio_snapshots', 'households', ['household_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('portfolio_snapshots_asset_id_fkey'), 'portfolio_snapshots', 'assets', ['asset_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('portfolio_snapshots_sub_portfolio_id_fkey'), 'portfolio_snapshots', 'sub_portfolios', ['sub_portfolio_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.alter_column('portfolio_snapshots', 'average_cost_basis',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'current_value_home_currency',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'current_price',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment='Separates AAPL in your Risky vs Core bags',
               existing_nullable=True)
    op.drop_constraint(None, 'portfolio_access', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_access', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_access_sub_portfolio_id_fkey'), 'portfolio_access', 'sub_portfolios', ['sub_portfolio_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('portfolio_access_user_id_fkey'), 'portfolio_access', 'users', ['user_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_portfolio_access_id'), table_name='portfolio_access')
    op.alter_column('portfolio_access', 'role',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'OWNER', 'VIEWER'",
               existing_nullable=True)
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.alter_column('households', 'name',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'The Smith Family' or 'Ivan Personal'",
               existing_nullable=True)
    op.drop_constraint(None, 'household_members', type_='foreignkey')
    op.drop_constraint(None, 'household_members', type_='foreignkey')
    op.create_foreign_key(op.f('household_members_household_id_fkey'), 'household_members', 'households', ['household_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('household_members_user_id_fkey'), 'household_members', 'users', ['user_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_household_members_id'), table_name='household_members')
    op.alter_column('household_members', 'role',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'ADMIN', 'EDITOR', 'VIEWER'",
               existing_nullable=True)
    op.drop_constraint(None, 'financial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('financial_accounts_household_id_fkey'), 'financial_accounts', 'households', ['household_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.alter_column('financial_accounts', 'tax_status',
               existing_type=sa.Enum('taxable', 'tax_deferred', 'tax_free', name='taxtreatment'),
               type_=postgresql.ENUM('taxable', 'tax_deferred', 'tax_free', name='tax_treatment'),
               existing_nullable=True)
    op.alter_column('financial_accounts', 'liquidity',
               existing_type=sa.Enum('liquid', 'market_liquid', 'time_locked', 'retirement', name='liquiditystatus'),
               type_=postgresql.ENUM('liquid', 'market_liquid', 'time_locked', 'retirement', name='liquidity_status'),
               existing_nullable=True)
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.create_foreign_key(op.f('dividends_sub_portfolio_id_fkey'), 'dividends', 'sub_portfolios', ['sub_portfolio_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('dividends_household_id_fkey'), 'dividends', 'households', ['household_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('dividends_asset_id_fkey'), 'dividends', 'assets', ['asset_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('dividends_account_id_fkey'), 'dividends', 'financial_accounts', ['account_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.alter_column('dividends', 'amount',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.alter_column('dividends', 'sub_portfolio_id',
               existing_type=sa.INTEGER(),
               comment='Assigns cash yield to the specific portfolio',
               existing_nullable=True)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_household_id_fkey'), 'categories', 'households', ['household_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               comment="'INCOME' or 'EXPENSE'",
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'Transport', 'Salary', 'Dividends'",
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_constraint(None, 'account_balances', type_='foreignkey')
    op.create_foreign_key(op.f('account_balances_account_id_fkey'), 'account_balances', 'financial_accounts', ['account_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_account_balances_id'), table_name='account_balances')
    op.alter_column('account_balances', 'balance',
               existing_type=sa.Numeric(),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    op.drop_constraint(None, 'account_access', type_='foreignkey')
    op.drop_constraint(None, 'account_access', type_='foreignkey')
    op.create_foreign_key(op.f('account_access_account_id_fkey'), 'account_access', 'financial_accounts', ['account_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('account_access_user_id_fkey'), 'account_access', 'users', ['user_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_account_access_id'), table_name='account_access')
    op.alter_column('account_access', 'role',
               existing_type=sa.VARCHAR(),
               comment="e.g., 'OWNER', 'VIEWER'",
               existing_nullable=True)
    # ### end Alembic commands ###
