"""recurring rules carry an mcc and a card category

Revision ID: 1abfa48d2200
Revises: 6b6dc0185293
Create Date: 2026-09-02 14:13:52.096327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abfa48d2200'
down_revision: Union[str, Sequence[str], None] = '6b6dc0185293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('mcc', sa.String(length=4), nullable=True), schema='finance_tracker')
    op.add_column('recurring_transactions', sa.Column('card_category_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_recurring_transactions_card_category_id'), 'recurring_transactions', ['card_category_id'], unique=False, schema='finance_tracker')
    # Named, not left to autogenerate's `None`: the downgrade has to drop it by
    # name, and `op.drop_constraint(None, ...)` fails.
    op.create_foreign_key(
        'fk_recurring_transactions_card_category_id',
        'recurring_transactions',
        'card_categories',
        ['card_category_id'],
        ['id'],
        source_schema='finance_tracker',
        referent_schema='finance_tracker',
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_recurring_transactions_card_category_id',
        'recurring_transactions',
        schema='finance_tracker',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_finance_tracker_recurring_transactions_card_category_id'), table_name='recurring_transactions', schema='finance_tracker')
    op.drop_column('recurring_transactions', 'card_category_id', schema='finance_tracker')
    op.drop_column('recurring_transactions', 'mcc', schema='finance_tracker')
    # ### end Alembic commands ###
