"""account institution grouping label

Revision ID: 23e0ec346885
Revises: b09a1f70183f
Create Date: 2026-09-11 00:11:02.821025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e0ec346885'
down_revision: Union[str, Sequence[str], None] = 'b09a1f70183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_accounts', sa.Column('institution', sa.String(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_accounts', 'institution', schema='finance_tracker')
    # ### end Alembic commands ###
