"""add_market_prices_and_snapshot_constraint

Revision ID: 2ea5dd401ec6
Revises: 3a8dd8f39502
Create Date: 2026-05-04 02:25:08.544074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea5dd401ec6'
down_revision: Union[str, Sequence[str], None] = '3a8dd8f39502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_market_price_ticker_date'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_market_prices_date'), 'market_prices', ['date'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_market_prices_id'), 'market_prices', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_market_prices_ticker'), 'market_prices', ['ticker'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_tracker_market_prices_ticker'), table_name='market_prices', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_market_prices_id'), table_name='market_prices', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_market_prices_date'), table_name='market_prices', schema='finance_tracker')
    op.drop_table('market_prices', schema='finance_tracker')
    # ### end Alembic commands ###
