"""update household to have owner column

Revision ID: 3a8dd8f39502
Revises: 8ef3a3270986
Create Date: 2026-05-01 21:40:42.520626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8dd8f39502'
down_revision: Union[str, Sequence[str], None] = '8ef3a3270986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('owner_id', sa.UUID(), nullable=False), schema='finance_tracker')
    op.create_foreign_key(None, 'households', 'users', ['owner_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'households', schema='finance_tracker', type_='foreignkey')
    op.drop_column('households', 'owner_id', schema='finance_tracker')
    # ### end Alembic commands ###
