"""add missing performance indexes

Revision ID: 67229e0d9c94
Revises: ee55ff66aa77
Create Date: 2026-07-25 16:40:53.760066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67229e0d9c94'
down_revision: Union[str, Sequence[str], None] = 'ee55ff66aa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_finance_tracker_account_access_account_id'), 'account_access', ['account_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_account_access_user_id'), 'account_access', ['user_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_account_balances_account_id_date'), table_name='account_balances', schema='finance_tracker')
    op.create_index('ix_account_balances_account_date', 'account_balances', ['account_id', 'date'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_budgets_category_id'), 'budgets', ['category_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_categories_household_id'), table_name='categories', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_categories_household_id'), 'categories', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_dividends_household_id_date'), table_name='dividends', schema='finance_tracker')
    op.create_index('ix_dividends_household_date', 'dividends', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_dividends_account_id'), 'dividends', ['account_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_dividends_asset_id'), 'dividends', ['asset_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_dividends_transaction_id'), 'dividends', ['transaction_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_financial_accounts_household_id'), table_name='financial_accounts', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_financial_accounts_household_id'), 'financial_accounts', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members', schema='finance_tracker')
    op.drop_index(op.f('ix_household_members_user_id'), table_name='household_members', schema='finance_tracker')
    op.create_index('ix_household_members_user_household', 'household_members', ['user_id', 'household_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_portfolio_access_sub_portfolio_id'), 'portfolio_access', ['sub_portfolio_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_portfolio_access_user_id'), 'portfolio_access', ['user_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_portfolio_snapshots_household_id_date'), table_name='portfolio_snapshots', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_portfolio_snapshots_asset_id'), 'portfolio_snapshots', ['asset_id'], unique=False, schema='finance_tracker')
    op.create_index('ix_portfolio_snapshots_household_date', 'portfolio_snapshots', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_scheduled_dividends_account_id'), 'scheduled_dividends', ['account_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_scheduled_dividends_asset_id'), 'scheduled_dividends', ['asset_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_scheduled_dividends_date'), 'scheduled_dividends', ['date'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_scheduled_dividends_dividend_id'), 'scheduled_dividends', ['dividend_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_scheduled_dividends_sub_portfolio_id'), 'scheduled_dividends', ['sub_portfolio_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_sub_portfolios_household_id'), table_name='sub_portfolios', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_sub_portfolios_household_id'), 'sub_portfolios', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_trades_household_id_date'), table_name='trades', schema='finance_tracker')
    op.drop_index(op.f('ix_trades_sub_portfolio_id'), table_name='trades', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_trades_account_id'), 'trades', ['account_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_trades_transaction_id'), 'trades', ['transaction_id'], unique=False, schema='finance_tracker')
    op.create_index('ix_trades_household_date', 'trades', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.create_index('ix_trades_sub_portfolio_asset', 'trades', ['sub_portfolio_id', 'asset_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_transactions_account_id_date'), table_name='transactions', schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_transactions_category_id'), 'transactions', ['category_id'], unique=False, schema='finance_tracker')
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_account_date', table_name='transactions', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_transactions_category_id'), table_name='transactions', schema='finance_tracker')
    op.create_index(op.f('ix_transactions_account_id_date'), 'transactions', ['account_id', 'date'], unique=False, schema='finance_tracker')
    op.drop_index('ix_trades_sub_portfolio_asset', table_name='trades', schema='finance_tracker')
    op.drop_index('ix_trades_household_date', table_name='trades', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_trades_transaction_id'), table_name='trades', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_trades_account_id'), table_name='trades', schema='finance_tracker')
    op.create_index(op.f('ix_trades_sub_portfolio_id'), 'trades', ['sub_portfolio_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_trades_household_id_date'), 'trades', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_sub_portfolios_household_id'), table_name='sub_portfolios', schema='finance_tracker')
    op.create_index(op.f('ix_sub_portfolios_household_id'), 'sub_portfolios', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_scheduled_dividends_sub_portfolio_id'), table_name='scheduled_dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_scheduled_dividends_dividend_id'), table_name='scheduled_dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_scheduled_dividends_date'), table_name='scheduled_dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_scheduled_dividends_asset_id'), table_name='scheduled_dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_scheduled_dividends_account_id'), table_name='scheduled_dividends', schema='finance_tracker')
    op.drop_index('ix_portfolio_snapshots_household_date', table_name='portfolio_snapshots', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_portfolio_snapshots_asset_id'), table_name='portfolio_snapshots', schema='finance_tracker')
    op.create_index(op.f('ix_portfolio_snapshots_household_id_date'), 'portfolio_snapshots', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_portfolio_access_user_id'), table_name='portfolio_access', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_portfolio_access_sub_portfolio_id'), table_name='portfolio_access', schema='finance_tracker')
    op.drop_index('ix_household_members_user_household', table_name='household_members', schema='finance_tracker')
    op.create_index(op.f('ix_household_members_user_id'), 'household_members', ['user_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_financial_accounts_household_id'), table_name='financial_accounts', schema='finance_tracker')
    op.create_index(op.f('ix_financial_accounts_household_id'), 'financial_accounts', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_dividends_transaction_id'), table_name='dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_dividends_asset_id'), table_name='dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_dividends_account_id'), table_name='dividends', schema='finance_tracker')
    op.drop_index('ix_dividends_household_date', table_name='dividends', schema='finance_tracker')
    op.create_index(op.f('ix_dividends_household_id_date'), 'dividends', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_categories_household_id'), table_name='categories', schema='finance_tracker')
    op.create_index(op.f('ix_categories_household_id'), 'categories', ['household_id'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_budgets_category_id'), table_name='budgets', schema='finance_tracker')
    op.drop_index('ix_account_balances_account_date', table_name='account_balances', schema='finance_tracker')
    op.create_index(op.f('ix_account_balances_account_id_date'), 'account_balances', ['account_id', 'date'], unique=False, schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_account_access_user_id'), table_name='account_access', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_account_access_account_id'), table_name='account_access', schema='finance_tracker')
    # ### end Alembic commands ###
