"""recurring rules carry a fee percentage

Revision ID: 67df3546a72a
Revises: b4d8e75c388c
Create Date: 2026-09-11 08:11:24.352555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67df3546a72a'
down_revision: Union[str, Sequence[str], None] = 'b4d8e75c388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('fee_percent', sa.Numeric(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'fee_percent', schema='finance_tracker')
    # ### end Alembic commands ###
