"""multi-way transaction splits and reusable counterparties

Revision ID: 6b6dc0185293
Revises: beea2ea972a2
Create Date: 2026-08-28 21:02:10.856050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6dc0185293'
down_revision: Union[str, Sequence[str], None] = 'beea2ea972a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_counterparties_household_name'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_counterparties_household_id'), 'counterparties', ['household_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_counterparties_id'), 'counterparties', ['id'], unique=False, schema='finance_tracker')

    # Backfill: one Counterparty per distinct (household, name) already in use
    # on a receivable/payable ledger account. "Alice" owing the household and
    # the household owing "Alice" collapse onto the same row here — the person
    # is one row, the two ledger accounts pointing at them stay separate.
    op.execute(
        """
        INSERT INTO finance_tracker.counterparties (id, household_id, name)
        SELECT gen_random_uuid(), household_id, counterparty_name
        FROM finance_tracker.ledger_accounts
        WHERE counterparty_name IS NOT NULL
        GROUP BY household_id, counterparty_name
        """
    )

    op.add_column('ledger_accounts', sa.Column('counterparty_id', sa.UUID(), nullable=True), schema='finance_tracker')

    # Backfill: point every receivable/payable account at the Counterparty row
    # matching its household and old free-text name.
    op.execute(
        """
        UPDATE finance_tracker.ledger_accounts AS la
        SET counterparty_id = c.id
        FROM finance_tracker.counterparties AS c
        WHERE c.household_id = la.household_id
          AND c.name = la.counterparty_name
        """
    )

    op.drop_constraint(op.f('uq_ledger_accounts_counterparty'), 'ledger_accounts', schema='finance_tracker', type_='unique')
    op.create_unique_constraint('uq_ledger_accounts_counterparty', 'ledger_accounts', ['household_id', 'role', 'counterparty_id', 'owner_user_id'], schema='finance_tracker')
    op.create_foreign_key(None, 'ledger_accounts', 'counterparties', ['counterparty_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker')
    op.drop_column('ledger_accounts', 'counterparty_name', schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_accounts', sa.Column('counterparty_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='finance_tracker')

    # Backfill the free-text name back from the Counterparty each account
    # pointed at, before the id column (and the table it references) go away.
    op.execute(
        """
        UPDATE finance_tracker.ledger_accounts AS la
        SET counterparty_name = c.name
        FROM finance_tracker.counterparties AS c
        WHERE c.id = la.counterparty_id
        """
    )

    op.drop_constraint(None, 'ledger_accounts', schema='finance_tracker', type_='foreignkey')
    op.drop_constraint('uq_ledger_accounts_counterparty', 'ledger_accounts', schema='finance_tracker', type_='unique')
    op.create_unique_constraint(op.f('uq_ledger_accounts_counterparty'), 'ledger_accounts', ['household_id', 'role', 'counterparty_name', 'owner_user_id'], schema='finance_tracker', postgresql_nulls_not_distinct=False)
    op.drop_column('ledger_accounts', 'counterparty_id', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_counterparties_id'), table_name='counterparties', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_counterparties_household_id'), table_name='counterparties', schema='finance_tracker')
    op.drop_table('counterparties', schema='finance_tracker')
    # ### end Alembic commands ###
