"""add_household_defaults

Revision ID: 7966345b6cf5
Revises: 0b51bc0dd274
Create Date: 2026-05-11 14:19:12.921568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7966345b6cf5'
down_revision: Union[str, Sequence[str], None] = '0b51bc0dd274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('default_funding_account_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.add_column('households', sa.Column('default_sub_portfolio_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_foreign_key(None, 'households', 'sub_portfolios', ['default_sub_portfolio_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker')
    op.create_foreign_key(None, 'households', 'financial_accounts', ['default_funding_account_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'households', schema='finance_tracker', type_='foreignkey')
    op.drop_constraint(None, 'households', schema='finance_tracker', type_='foreignkey')
    op.drop_column('households', 'default_sub_portfolio_id', schema='finance_tracker')
    op.drop_column('households', 'default_funding_account_id', schema='finance_tracker')
    # ### end Alembic commands ###
