"""Initial schema with UUIDs

Revision ID: 8ef3a3270986
Revises: 
Create Date: 2026-05-01 19:01:44.692965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef3a3270986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_assets_id'), 'assets', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_assets_ticker'), 'assets', ['ticker'], unique=False, schema='finance_tracker')
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('target_currency', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_exchange_rates_id'), 'exchange_rates', ['id'], unique=False, schema='finance_tracker')
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_households_id'), 'households', ['id'], unique=False, schema='finance_tracker')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('preferred_timezone', sa.String(), nullable=False),
    sa.Column('salted_hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_users_email'), 'users', ['email'], unique=True, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_users_id'), 'users', ['id'], unique=False, schema='finance_tracker')
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_categories_id'), 'categories', ['id'], unique=False, schema='finance_tracker')
    op.create_table('financial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('liquidity', sa.Enum('liquid', 'market_liquid', 'time_locked', 'retirement', name='liquidity_status', schema='finance_tracker'), nullable=True),
    sa.Column('tax_status', sa.Enum('taxable', 'tax_deferred', 'tax_free', name='tax_treatment', schema='finance_tracker'), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_financial_accounts_id'), 'financial_accounts', ['id'], unique=False, schema='finance_tracker')
    op.create_table('household_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='household_role_type', schema='finance_tracker'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['finance_tracker.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_household_members_id'), 'household_members', ['id'], unique=False, schema='finance_tracker')
    op.create_table('sub_portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_sub_portfolios_id'), 'sub_portfolios', ['id'], unique=False, schema='finance_tracker')
    op.create_table('account_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='account_role_type', schema='finance_tracker'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_tracker.financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['finance_tracker.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_account_access_id'), 'account_access', ['id'], unique=False, schema='finance_tracker')
    op.create_table('account_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_tracker.financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_account_balances_id'), 'account_balances', ['id'], unique=False, schema='finance_tracker')
    op.create_table('dividends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('sub_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_tracker.financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_tracker.assets.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['sub_portfolio_id'], ['finance_tracker.sub_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_dividends_id'), 'dividends', ['id'], unique=False, schema='finance_tracker')
    op.create_table('portfolio_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sub_portfolio_id'], ['finance_tracker.sub_portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['finance_tracker.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_portfolio_access_id'), 'portfolio_access', ['id'], unique=False, schema='finance_tracker')
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('sub_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Numeric(), nullable=True),
    sa.Column('exchange_rate_used', sa.Float(), nullable=True),
    sa.Column('current_value_home_currency', sa.Numeric(), nullable=True),
    sa.Column('average_cost_basis', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_tracker.assets.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['sub_portfolio_id'], ['finance_tracker.sub_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False, schema='finance_tracker')
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('sub_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('trade_type', sa.Enum('buy', 'sell', name='trade_type', schema='finance_tracker'), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_tracker.financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_tracker.assets.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['sub_portfolio_id'], ['finance_tracker.sub_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_trades_id'), 'trades', ['id'], unique=False, schema='finance_tracker')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transaction_type', schema='finance_tracker'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_tracker.financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_tracker.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_transactions_id'), 'transactions', ['id'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_tracker_transactions_id'), table_name='transactions', schema='finance_tracker')
    op.drop_table('transactions', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_trades_id'), table_name='trades', schema='finance_tracker')
    op.drop_table('trades', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_portfolio_snapshots_id'), table_name='portfolio_snapshots', schema='finance_tracker')
    op.drop_table('portfolio_snapshots', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_portfolio_access_id'), table_name='portfolio_access', schema='finance_tracker')
    op.drop_table('portfolio_access', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_dividends_id'), table_name='dividends', schema='finance_tracker')
    op.drop_table('dividends', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_account_balances_id'), table_name='account_balances', schema='finance_tracker')
    op.drop_table('account_balances', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_account_access_id'), table_name='account_access', schema='finance_tracker')
    op.drop_table('account_access', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_sub_portfolios_id'), table_name='sub_portfolios', schema='finance_tracker')
    op.drop_table('sub_portfolios', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_household_members_id'), table_name='household_members', schema='finance_tracker')
    op.drop_table('household_members', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_financial_accounts_id'), table_name='financial_accounts', schema='finance_tracker')
    op.drop_table('financial_accounts', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_categories_id'), table_name='categories', schema='finance_tracker')
    op.drop_table('categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_users_id'), table_name='users', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_users_email'), table_name='users', schema='finance_tracker')
    op.drop_table('users', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_households_id'), table_name='households', schema='finance_tracker')
    op.drop_table('households', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_exchange_rates_id'), table_name='exchange_rates', schema='finance_tracker')
    op.drop_table('exchange_rates', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_assets_ticker'), table_name='assets', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_assets_id'), table_name='assets', schema='finance_tracker')
    op.drop_table('assets', schema='finance_tracker')
    # ### end Alembic commands ###
