"""add user default account

Revision ID: 956575644b4d
Revises: 67229e0d9c94
Create Date: 2026-07-26 09:32:50.517977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956575644b4d'
down_revision: Union[str, Sequence[str], None] = '67229e0d9c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_account_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_foreign_key(None, 'users', 'financial_accounts', ['default_account_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='finance_tracker', type_='foreignkey')
    op.drop_column('users', 'default_account_id', schema='finance_tracker')
    # ### end Alembic commands ###
