"""add_unique_constraint_to_snapshots

Revision ID: 9d0dae805819
Revises: f6a7b8c9d0e1
Create Date: 2026-05-09 16:46:50.191987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0dae805819'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_balances', 'is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='finance_tracker')
    op.create_unique_constraint('uq_exchange_rate_base_target_date', 'exchange_rates', ['base_currency', 'target_currency', 'date'], schema='finance_tracker')
    op.create_unique_constraint('uq_portfolio_snapshot_sub_portfolio_asset_date', 'portfolio_snapshots', ['sub_portfolio_id', 'asset_id', 'date'], schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_portfolio_snapshot_sub_portfolio_asset_date', 'portfolio_snapshots', schema='finance_tracker', type_='unique')
    op.drop_constraint('uq_exchange_rate_base_target_date', 'exchange_rates', schema='finance_tracker', type_='unique')
    op.alter_column('account_balances', 'is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='finance_tracker')
    # ### end Alembic commands ###
