"""card categories can count towards several limits

Revision ID: 9de9dad096e1
Revises: ec48a42c1dda
Create Date: 2026-09-13 10:39:51.147672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de9dad096e1'
down_revision: Union[str, Sequence[str], None] = 'ec48a42c1dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_limit_categories',
    sa.Column('limit_id', sa.UUID(), nullable=False),
    sa.Column('card_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_category_id'], ['finance_tracker.card_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['limit_id'], ['finance_tracker.card_limits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('limit_id', 'card_category_id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_card_limit_categories_card_category_id'), 'card_limit_categories', ['card_category_id'], unique=False, schema='finance_tracker')
    # Carry every existing link across before the column goes, or upgrading
    # would silently un-meter every card limit a user had set up.
    op.execute(
        """
        INSERT INTO finance_tracker.card_limit_categories (limit_id, card_category_id)
        SELECT limit_id, id FROM finance_tracker.card_categories
        WHERE limit_id IS NOT NULL
        """
    )
    op.drop_index(op.f('ix_finance_tracker_card_categories_limit_id'), table_name='card_categories', schema='finance_tracker')
    op.drop_constraint(op.f('card_categories_limit_id_fkey'), 'card_categories', schema='finance_tracker', type_='foreignkey')
    op.drop_column('card_categories', 'limit_id', schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_categories', sa.Column('limit_id', sa.UUID(), autoincrement=False, nullable=True), schema='finance_tracker')
    op.create_foreign_key(op.f('card_categories_limit_id_fkey'), 'card_categories', 'card_limits', ['limit_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker', ondelete='SET NULL')
    op.create_index(op.f('ix_finance_tracker_card_categories_limit_id'), 'card_categories', ['limit_id'], unique=False, schema='finance_tracker')
    # The old column holds one limit per category, so a category counting
    # towards several keeps only one of them: the earliest-created, which is
    # the one it had before it could have more.
    op.execute(
        """
        UPDATE finance_tracker.card_categories AS c
        SET limit_id = (
            SELECT l.id
            FROM finance_tracker.card_limit_categories AS lc
            JOIN finance_tracker.card_limits AS l ON l.id = lc.limit_id
            WHERE lc.card_category_id = c.id
            ORDER BY l.created_at, l.id
            LIMIT 1
        )
        """
    )
    op.drop_index(op.f('ix_finance_tracker_card_limit_categories_card_category_id'), table_name='card_limit_categories', schema='finance_tracker')
    op.drop_table('card_limit_categories', schema='finance_tracker')
    # ### end Alembic commands ###
