"""card default foreign fee percent

Revision ID: a99f4f931781
Revises: 405757fbb34e
Create Date: 2026-09-13 23:34:16.202139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99f4f931781'
down_revision: Union[str, Sequence[str], None] = '405757fbb34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('foreign_fee_percent', sa.Numeric(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'foreign_fee_percent', schema='finance_tracker')
    # ### end Alembic commands ###
