"""cards, card categories and spend limits

Revision ID: aaab87fc3613
Revises: b8202b0863cd
Create Date: 2026-08-28 01:45:08.300044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaab87fc3613'
down_revision: Union[str, Sequence[str], None] = 'b8202b0863cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_account_id', sa.UUID(), nullable=False),
    sa.Column('cycle_basis', sa.Enum('statement', 'calendar', name='cyclebasis', native_enum=False), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_account_id'], ['finance_tracker.financial_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_cards_financial_account_id'), 'cards', ['financial_account_id'], unique=True, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_cards_id'), 'cards', ['id'], unique=False, schema='finance_tracker')
    op.create_table('card_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('direction', sa.Enum('ceiling', 'floor', name='limitdirection', native_enum=False), nullable=False),
    sa.Column('reset_basis', sa.Enum('cycle', 'calendar_month', 'quarter', 'year', name='limitresetbasis', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['finance_tracker.cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_card_limits_card_id'), 'card_limits', ['card_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_card_limits_id'), 'card_limits', ['id'], unique=False, schema='finance_tracker')
    op.create_table('card_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('limit_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['finance_tracker.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['limit_id'], ['finance_tracker.card_limits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'name', name='uq_card_category_card_name'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_card_categories_card_id'), 'card_categories', ['card_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_card_categories_id'), 'card_categories', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_card_categories_limit_id'), 'card_categories', ['limit_id'], unique=False, schema='finance_tracker')
    op.add_column('transactions', sa.Column('card_category_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_transactions_card_category_id'), 'transactions', ['card_category_id'], unique=False, schema='finance_tracker')
    op.create_foreign_key(None, 'transactions', 'card_categories', ['card_category_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='finance_tracker', type_='foreignkey')
    op.drop_index(op.f('ix_finance_tracker_transactions_card_category_id'), table_name='transactions', schema='finance_tracker')
    op.drop_column('transactions', 'card_category_id', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_card_categories_limit_id'), table_name='card_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_card_categories_id'), table_name='card_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_card_categories_card_id'), table_name='card_categories', schema='finance_tracker')
    op.drop_table('card_categories', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_card_limits_id'), table_name='card_limits', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_card_limits_card_id'), table_name='card_limits', schema='finance_tracker')
    op.drop_table('card_limits', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_cards_id'), table_name='cards', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_cards_financial_account_id'), table_name='cards', schema='finance_tracker')
    op.drop_table('cards', schema='finance_tracker')
    # ### end Alembic commands ###
