"""recurring rules can carry a standing split

Revision ID: b09a1f70183f
Revises: 1abfa48d2200
Create Date: 2026-09-02 14:46:01.699427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09a1f70183f'
down_revision: Union[str, Sequence[str], None] = '1abfa48d2200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transaction_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurring_transaction_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['finance_tracker.counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurring_transaction_id'], ['finance_tracker.recurring_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_transaction_id', 'counterparty_id', name='uq_recurring_split_rule_counterparty'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_recurring_transaction_splits_counterparty_id'), 'recurring_transaction_splits', ['counterparty_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_recurring_transaction_splits_id'), 'recurring_transaction_splits', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_recurring_transaction_splits_recurring_transaction_id'), 'recurring_transaction_splits', ['recurring_transaction_id'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_tracker_recurring_transaction_splits_recurring_transaction_id'), table_name='recurring_transaction_splits', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_recurring_transaction_splits_id'), table_name='recurring_transaction_splits', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_recurring_transaction_splits_counterparty_id'), table_name='recurring_transaction_splits', schema='finance_tracker')
    op.drop_table('recurring_transaction_splits', schema='finance_tracker')
    # ### end Alembic commands ###
