"""Add transfer_id to Transaction

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-08 01:05:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_transactions_transfer_id'), 'transactions', ['transfer_id'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_tracker_transactions_transfer_id'), table_name='transactions', schema='finance_tracker')
    op.drop_column('transactions', 'transfer_id', schema='finance_tracker')
    # ### end Alembic commands ###
