"""per-transaction fee percentage

Revision ID: b4d8e75c388c
Revises: 23e0ec346885
Create Date: 2026-09-11 08:08:13.663236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d8e75c388c'
down_revision: Union[str, Sequence[str], None] = '23e0ec346885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fee_percent', sa.Numeric(), nullable=True), schema='finance_tracker')
    op.add_column('transactions', sa.Column('fee_for_transaction_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_transactions_fee_for_transaction_id'), 'transactions', ['fee_for_transaction_id'], unique=False, schema='finance_tracker')
    op.create_foreign_key(None, 'transactions', 'transactions', ['fee_for_transaction_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='finance_tracker', type_='foreignkey')
    op.drop_index(op.f('ix_finance_tracker_transactions_fee_for_transaction_id'), table_name='transactions', schema='finance_tracker')
    op.drop_column('transactions', 'fee_for_transaction_id', schema='finance_tracker')
    op.drop_column('transactions', 'fee_percent', schema='finance_tracker')
    # ### end Alembic commands ###
