"""per-user setting to record merchant codes

Revision ID: b8202b0863cd
Revises: fbfb41d8874a
Create Date: 2026-08-26 23:46:21.757329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8202b0863cd'
down_revision: Union[str, Sequence[str], None] = 'fbfb41d8874a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('record_merchant_codes', sa.Boolean(), server_default='false', nullable=False), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'record_merchant_codes', schema='finance_tracker')
    # ### end Alembic commands ###
