"""archive accounts instead of deleting used ones

Revision ID: bc4ae7e4cd64
Revises: aaab87fc3613
Create Date: 2026-08-28 09:35:48.447918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4ae7e4cd64'
down_revision: Union[str, Sequence[str], None] = 'aaab87fc3613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_accounts', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_accounts', 'is_archived', schema='finance_tracker')
    # ### end Alembic commands ###
