"""link financial accounts to sub-portfolios

Revision ID: de66db52f0b9
Revises: 1754a7384d79
Create Date: 2026-08-17 22:14:52.865643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de66db52f0b9'
down_revision: Union[str, Sequence[str], None] = '1754a7384d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Autogenerate emitted this FK as `None`, which leaves downgrade() trying to drop a
# constraint by that name and failing. Named explicitly so the migration is reversible.
FK_NAME = "fk_financial_accounts_sub_portfolio_id"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_accounts', sa.Column('sub_portfolio_id', sa.UUID(), nullable=True), schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_financial_accounts_sub_portfolio_id'), 'financial_accounts', ['sub_portfolio_id'], unique=False, schema='finance_tracker')
    op.create_foreign_key(FK_NAME, 'financial_accounts', 'sub_portfolios', ['sub_portfolio_id'], ['id'], source_schema='finance_tracker', referent_schema='finance_tracker', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'financial_accounts', schema='finance_tracker', type_='foreignkey')
    op.drop_index(op.f('ix_finance_tracker_financial_accounts_sub_portfolio_id'), table_name='financial_accounts', schema='finance_tracker')
    op.drop_column('financial_accounts', 'sub_portfolio_id', schema='finance_tracker')
    # ### end Alembic commands ###
