"""add_description_to_trades

Revision ID: eb107a14bb34
Revises: 7966345b6cf5
Create Date: 2026-05-11 14:37:22.551180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb107a14bb34'
down_revision: Union[str, Sequence[str], None] = '7966345b6cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('description', sa.String(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'description', schema='finance_tracker')
    # ### end Alembic commands ###
