"""card anniversary date

Revision ID: ec48a42c1dda
Revises: b09a1f70183f
Create Date: 2026-09-12 10:57:14.310512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec48a42c1dda'
down_revision: Union[str, Sequence[str], None] = 'b09a1f70183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('anniversary_date', sa.Date(), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'anniversary_date', schema='finance_tracker')
    # ### end Alembic commands ###
