"""add double-entry ledger

Revision ID: ed5b3b05957f
Revises: de66db52f0b9
Create Date: 2026-08-25 23:09:54.860164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5b3b05957f'
down_revision: Union[str, Sequence[str], None] = 'de66db52f0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'transaction', 'transfer', 'trade', 'dividend', 'balance_adjustment', 'opening_balance', name='journal_source', schema='finance_tracker'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_journal_entries_source'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_journal_entries_household_id'), 'journal_entries', ['household_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_journal_entries_id'), 'journal_entries', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_journal_entries_source_id'), 'journal_entries', ['source_id'], unique=False, schema='finance_tracker')
    op.create_index('ix_journal_entries_household_date', 'journal_entries', ['household_id', 'date'], unique=False, schema='finance_tracker')
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'income', 'expense', name='ledger_account_type', schema='finance_tracker'), nullable=False),
    sa.Column('role', sa.Enum('cash', 'category', 'receivable', 'payable', 'opening_balance', 'adjustment', name='ledger_account_role', schema='finance_tracker'), nullable=False),
    sa.Column('is_contra', sa.Boolean(), nullable=False),
    sa.Column('financial_account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['finance_tracker.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['finance_tracker.financial_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['finance_tracker.households.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['finance_tracker.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', name='uq_ledger_accounts_category'),
    sa.UniqueConstraint('financial_account_id', name='uq_ledger_accounts_financial_account'),
    sa.UniqueConstraint('household_id', 'role', 'counterparty_name', 'owner_user_id', name='uq_ledger_accounts_counterparty'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_ledger_accounts_household_id'), 'ledger_accounts', ['household_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_ledger_accounts_id'), 'ledger_accounts', ['id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_ledger_accounts_owner_user_id'), 'ledger_accounts', ['owner_user_id'], unique=False, schema='finance_tracker')
    op.create_index('ix_ledger_accounts_household_role', 'ledger_accounts', ['household_id', 'role'], unique=False, schema='finance_tracker')
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('ledger_account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(), nullable=False),
    sa.Column('credit', sa.Numeric(), nullable=False),
    sa.Column('native_amount', sa.Numeric(), nullable=True),
    sa.Column('native_currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['finance_tracker.journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['finance_tracker.ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_tracker'
    )
    op.create_index(op.f('ix_finance_tracker_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False, schema='finance_tracker')
    op.create_index(op.f('ix_finance_tracker_journal_lines_id'), 'journal_lines', ['id'], unique=False, schema='finance_tracker')
    op.create_index('ix_journal_lines_account', 'journal_lines', ['ledger_account_id'], unique=False, schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_lines_account', table_name='journal_lines', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_journal_lines_id'), table_name='journal_lines', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_journal_lines_entry_id'), table_name='journal_lines', schema='finance_tracker')
    op.drop_table('journal_lines', schema='finance_tracker')
    op.drop_index('ix_ledger_accounts_household_role', table_name='ledger_accounts', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_ledger_accounts_owner_user_id'), table_name='ledger_accounts', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_ledger_accounts_id'), table_name='ledger_accounts', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_ledger_accounts_household_id'), table_name='ledger_accounts', schema='finance_tracker')
    op.drop_table('ledger_accounts', schema='finance_tracker')
    op.drop_index('ix_journal_entries_household_date', table_name='journal_entries', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_journal_entries_source_id'), table_name='journal_entries', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_journal_entries_id'), table_name='journal_entries', schema='finance_tracker')
    op.drop_index(op.f('ix_finance_tracker_journal_entries_household_id'), table_name='journal_entries', schema='finance_tracker')
    op.drop_table('journal_entries', schema='finance_tracker')
    # ### end Alembic commands ###
