"""record optional MCC on transactions

Revision ID: fbfb41d8874a
Revises: de66db52f0b9
Create Date: 2026-08-26 19:19:26.082682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfb41d8874a'
down_revision: Union[str, Sequence[str], None] = 'ed5b3b05957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('mcc', sa.String(length=4), nullable=True), schema='finance_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'mcc', schema='finance_tracker')
    # ### end Alembic commands ###
