package com.ivanlee.financetracker.ui.theme

import androidx.compose.ui.graphics.Color

// Generated by android/scripts/gen_palettes.py from the web frontend's Tailwind palette
// (frontend/node_modules/tailwindcss/theme.css, oklch converted to sRGB). Same scales the
// web dashboard's ThemeContext and the iOS ThemePalettes.swift use. Do not edit by hand.

object ThemePalettes {
    val all: Map<String, Palette> = mapOf(
        "sky" to Palette(mapOf(50 to Color(0xFFF0F9FF), 100 to Color(0xFFDFF2FE), 200 to Color(0xFFB8E6FE), 300 to Color(0xFF74D4FF), 400 to Color(0xFF00BCFF), 500 to Color(0xFF00A6F4), 600 to Color(0xFF0084D1), 700 to Color(0xFF0069A8), 800 to Color(0xFF00598A), 900 to Color(0xFF024A70), 950 to Color(0xFF052F4A))),
        "indigo" to Palette(mapOf(50 to Color(0xFFEEF2FF), 100 to Color(0xFFE0E7FF), 200 to Color(0xFFC6D2FF), 300 to Color(0xFFA3B3FF), 400 to Color(0xFF7C86FF), 500 to Color(0xFF615FFF), 600 to Color(0xFF4F39F6), 700 to Color(0xFF432DD7), 800 to Color(0xFF372AAC), 900 to Color(0xFF312C85), 950 to Color(0xFF1E1A4D))),
        "rose" to Palette(mapOf(50 to Color(0xFFFFF1F2), 100 to Color(0xFFFFE4E6), 200 to Color(0xFFFFCCD3), 300 to Color(0xFFFFA1AD), 400 to Color(0xFFFF637E), 500 to Color(0xFFFF2056), 600 to Color(0xFFEC003F), 700 to Color(0xFFC70036), 800 to Color(0xFFA50036), 900 to Color(0xFF8B0836), 950 to Color(0xFF4D0218))),
        "emerald" to Palette(mapOf(50 to Color(0xFFECFDF5), 100 to Color(0xFFD0FAE5), 200 to Color(0xFFA4F4CF), 300 to Color(0xFF5EE9B5), 400 to Color(0xFF00D492), 500 to Color(0xFF00BC7D), 600 to Color(0xFF009966), 700 to Color(0xFF007A55), 800 to Color(0xFF006045), 900 to Color(0xFF004F3B), 950 to Color(0xFF002C22))),
        "blue" to Palette(mapOf(50 to Color(0xFFEFF6FF), 100 to Color(0xFFDBEAFE), 200 to Color(0xFFBEDBFF), 300 to Color(0xFF8EC5FF), 400 to Color(0xFF51A2FF), 500 to Color(0xFF2B7FFF), 600 to Color(0xFF155DFC), 700 to Color(0xFF1447E6), 800 to Color(0xFF193CB8), 900 to Color(0xFF1C398E), 950 to Color(0xFF162456))),
        "fuchsia" to Palette(mapOf(50 to Color(0xFFFDF4FF), 100 to Color(0xFFFAE8FF), 200 to Color(0xFFF6CFFF), 300 to Color(0xFFF4A8FF), 400 to Color(0xFFED6AFF), 500 to Color(0xFFE12AFB), 600 to Color(0xFFC800DE), 700 to Color(0xFFA800B7), 800 to Color(0xFF8A0194), 900 to Color(0xFF721378), 950 to Color(0xFF4B004F))),
        "orange" to Palette(mapOf(50 to Color(0xFFFFF7ED), 100 to Color(0xFFFFEDD4), 200 to Color(0xFFFFD6A7), 300 to Color(0xFFFFB86A), 400 to Color(0xFFFF8904), 500 to Color(0xFFFF6900), 600 to Color(0xFFF54900), 700 to Color(0xFFCA3500), 800 to Color(0xFF9F2D00), 900 to Color(0xFF7E2A0C), 950 to Color(0xFF441306))),
        "yellow" to Palette(mapOf(50 to Color(0xFFFEFCE8), 100 to Color(0xFFFEF9C2), 200 to Color(0xFFFFF085), 300 to Color(0xFFFFDF20), 400 to Color(0xFFFDC700), 500 to Color(0xFFF0B100), 600 to Color(0xFFD08700), 700 to Color(0xFFA65F00), 800 to Color(0xFF894B00), 900 to Color(0xFF733E0A), 950 to Color(0xFF432004))),
        "mauve" to Palette(mapOf(50 to Color(0xFFFAFAFA), 100 to Color(0xFFF3F1F3), 200 to Color(0xFFE7E4E7), 300 to Color(0xFFD7D0D7), 400 to Color(0xFFA89EA9), 500 to Color(0xFF79697B), 600 to Color(0xFF594C5B), 700 to Color(0xFF463947), 800 to Color(0xFF2A212C), 900 to Color(0xFF1D161E), 950 to Color(0xFF0C090C))),
        "slate" to Palette(mapOf(50 to Color(0xFFF8FAFC), 100 to Color(0xFFF1F5F9), 200 to Color(0xFFE2E8F0), 300 to Color(0xFFCAD5E2), 400 to Color(0xFF90A1B9), 500 to Color(0xFF62748E), 600 to Color(0xFF45556C), 700 to Color(0xFF314158), 800 to Color(0xFF1D293D), 900 to Color(0xFF0F172B), 950 to Color(0xFF020618))),
    )
}
